Add tests for inline-token

diff --git a/tests/inline-token/check-test-output b/tests/inline-token/check-test-output
--- a/tests/inline-token/check-test-output
+++ b/tests/inline-token/check-test-output
@@ -4,25 +4,44 @@
 #
 set -eu -o pipefail
 
+# Print faulty output and error message
 error() {
-  echo "Error: $*" >&2
+  file=$1
+  msg=$2
+  {
+    echo "--- $file ---"
+    cat "$file"
+    echo "Error: $msg"
+  } >&2
   exit 1
 }
 
-out=test.out/ok/hello.cst
-if grep -q Blank "$out"; then
-  ./parse --output-json test/ok/hello
-  error "Found 'Blank' in parsing output [$out]"
-fi
+# token() constructs fall into 3 categories:
+# - extracted into their own named rule
+# - left in place and resulting in a node in the CST
+# - left in place and resulting in a missing node in the CST -> Blank
+#
+# Consult src/grammar.json to see the actual grammar after the simplify-grammar
+# pass.
+#
+expect_node="hello f g h i l s t u v field1"
+expect_missing_node="j w"
+expect_new_rule="goodbye a k mm n x y z field2"
 
-out=test.out/ok/goodbye.cst
-if grep -q Blank "$out"; then
-  ./parse --output-json test/ok/goodbye
-  error "Found 'Blank' in parsing output [$out]"
-fi
+for x in $expect_node; do
+  echo "$x: Check parsing output. Expect simple node for the token."
+  out=test.out/ok/$x.cst
+  grep -q '"'"$x"'"' "$out" || error "$out" "Unexpected output in $out"
+done
 
-out=test.out/ok/a.cst
-if grep -q Blank "$out"; then
-  ./parse --output-json test/ok/a
-  error "Found 'Blank' in parsing output [$out]"
-fi
+for x in $expect_missing_node; do
+  echo "$x: Check parsing output. Expect missing node for the token."
+  out=test.out/ok/$x.cst
+  grep -q "Blank" "$out" || error "$out" "Unexpected output in $out"
+done
+
+for x in $expect_new_rule; do
+  echo "$x: Check parsing output. Expect named rule for the token."
+  out=test.out/ok/$x.cst
+  grep -q "tok_" "$out" || error "$out" "Unexpected output in $out"
+done
