Use pkg-config to locate the tree-sitter library.

diff --git a/scripts/configure-tree-sitter b/scripts/configure-tree-sitter
--- a/scripts/configure-tree-sitter
+++ b/scripts/configure-tree-sitter
@@ -11,81 +11,48 @@ set -eu
 config_sh=config.sh
 config_mk=config.mk
 
-if [[ ! -e tree-sitter ]]; then
-  git clone --depth 1 https://github.com/tree-sitter/tree-sitter.git
-fi
+error() {
+  echo "Error: $*" >&2
+  exit 1
+}
 
-# Try to detect whether we want to use glibc and dynamic linking,
-# or musl and static linking.
-#
-use_musl=false
-case "$(opam switch show)" in
-  *+musl+*)
-    echo "Attempting configuration for musl and static linking."
-    use_musl=true
-    ;;
-  *)
-    echo "Using default configuration suitable for glibc and dynamic linking."
-esac
+pkg-config tree-sitter || error "The tree-sitter library can't be found.
+Consider installing it with './scripts/install-tree-sitter-lib'."
 
-if [[ "$use_musl" = true ]]; then
-  CC=musl-gcc
-else
-  CC=gcc
+if [[ -z "${TREESITTER_INCDIR+x}" ]]; then
+  TREESITTER_INCDIR=$(
+    pkg-config --cflags-only-I tree-sitter \
+    | sed -e 's/^-I//'
+  )
 fi
-export CC
+export TREESITTER_INCDIR
 
-if [[ -z "${PREFIX+x}" ]]; then
-  PREFIX=/usr/local
+if [[ -z "${TREESITTER_LIBDIR+x}" ]]; then
+  TREESITTER_LIBDIR=$(
+    pkg-config --libs-only-L tree-sitter \
+    | sed -e 's/^-L//'
+  )
 fi
-export PREFIX
-
-if [[ -z "${INCLUDEDIR+x}" ]]; then
-  if [[ "$use_musl" = true ]]; then
-    INCLUDEDIR="/usr/include/x86_64-linux-musl"
-  else
-    INCLUDEDIR="$PREFIX"/include
-  fi
-fi
-export INCLUDEDIR
-
-if [[ -z "${LIBDIR+x}" ]]; then
-  if [[ "$use_musl" = true ]]; then
-    LIBDIR="/usr/lib/x86_64-linux-musl"
-  else
-    LIBDIR="$PREFIX"/lib
-  fi
-fi
-export LIBDIR
+export TREESITTER_LIBDIR
 
 cat <<EOF
-Config for libtree-sitter:
-  CC: $CC
-  PREFIX: $PREFIX
-  INCLUDEDIR: $INCLUDEDIR
-  LIBDIR: $LIBDIR
+Config for using libtree-sitter:
+  TREESITTER_INCDIR: $TREESITTER_INCDIR
+  TREESITTER_LIBDIR: $TREESITTER_LIBDIR
 Config file for bash: $config_sh
 Config file for make: $config_mk
 EOF
 
 cat > "$config_sh" <<EOF
-# Config for libtree-sitter, generated by $0
-
-# C compiler
-CC="$CC"
-export CC
-
-# Default install prefix
-PREFIX="$PREFIX"
-export PREFIX
+# Config for using libtree-sitter, generated by '$0' using pkg-config.
 
 # Where the C headers get installed, in particular 'tree_sitter/api.h'.
-INCLUDEDIR="$INCLUDEDIR"
-export INCLUDEDIR
+TREESITTER_INCDIR="$TREESITTER_INCDIR"
+export TREESITTER_INCDIR
 
 # Where the tree-sitter runtime library gets installed.
-LIBDIR="$LIBDIR"
-export LIBDIR
+TREESITTER_LIBDIR="$TREESITTER_LIBDIR"
+export TREESITTER_LIBDIR
 EOF
 
 # It's a polyglot config file!
